version: "3.9"

services:
  tracker:
    image: "ghcr.io/wjr1985/meds_tracker:main"
    environment:
      GOOGLE_CREDS_PATH: ${GOOGLE_CREDS_PATH}
      TOKEN_PATH: ${TOKEN_PATH}
      SHEET_ID: ${SHEET_ID}
      TZ: ${TZ}
  authorize:
    image: "ghcr.io/wjr1985/meds_tracker:main"
    build: .
    environment:
      GOOGLE_CREDS_PATH: ${GOOGLE_CREDS_PATH}
      TOKEN_PATH: ${TOKEN_PATH}
      SHEET_ID: ${SHEET_ID}
      TZ: ${TZ}
    command: ["bundle", "exec", "ruby", "authorize.rb"]
    profiles: ["authorize"] 


