version: "3.9"

services:
  tracker:
    build: .
    ports: 
      - "4567:4567"
    volumes:
      - ".:/app"
    environment:
      GOOGLE_CREDS_PATH: ${GOOGLE_CREDS_PATH}
      TOKEN_PATH: ${TOKEN_PATH}
      SHEET_ID: ${SHEET_ID}
      TZ: ${TZ}
  authorize:
    build: .
    ports:
      - "5151:5151"
    volumes:
      - ".:/app"
    environment:
      GOOGLE_CREDS_PATH: ${GOOGLE_CREDS_PATH}
      TOKEN_PATH: ${TOKEN_PATH}
      SHEET_ID: ${SHEET_ID}
      TZ: ${TZ}
    command: ["bundle", "exec", "ruby", "authorize.rb"]
    profiles: ["authorize"] 


