version: "3.9"

services:
  tracker:
    ports:
      - "${MEDS_PORT:-4567}:4567"
    volumes:
      - "${MEDS_CREDS_PATH:./creds}:/app/creds"
  authorize:
    ports:
      - "${MEDS_AUTHORIZE_PORT:-5151}:5151"
    volumes:
      - "${MEDS_CREDS_PATH:./creds}:/app/creds"

